apiVersion: apps/v1
kind: Deployment
metadata:
  name: syseps-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syseps-api
  template:
    metadata:
      labels:
        app: syseps-api
    spec:
      containers:
        - name: syseps-api
          image: syseps-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: syseps-api-service
spec:
  selector:
    app: syseps-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

